### ISSUE TITLE
Many gradients mess up the display

### ISSUE THREAD

**Issue by winhowes** [webBoxio/atom-color#33]
In my css I had this:

```css
hr.soften {
  height: 1px;
  background-image: -webkit-linear-gradient(left, rgba(255,255,255,0), rgba(255,255,255,.8), rgba(255,255,255,0));
  background-image:    -moz-linear-gradient(left, rgba(255,255,255,0), rgba(255,255,255,.8), rgba(255,255,255,0));
  background-image:     -ms-linear-gradient(left, rgba(255,255,255,0), rgba(255,255,255,.8), rgba(255,255,255,0));
  background-image:      -o-linear-gradientt(left, rgba(255,255,255,0), rgba(255,255,255,.8), rgba(255,255,255,0));
  border: 0;
}
```

Here's how it displays:
<img width="975" alt="screen shot 2015-10-28 at 9 01 55 pm" src="https://cloud.githubusercontent.com/assets/7106166/10809790/2b3538aa-7db7-11e5-9a8e-1755f7bbaa97.png">

Disabling the package fixed the issue. I later restarted Atom (which also corrected the issue, but I thought I should give you a heads up).
